Version: 0.1.0
CompanyName: Zhiyang Chen
FileDescription: Generate Config for XlsxMerger.
InternalName: Config Generater
LegalCopyright: © Zhiyang Chen. All rights reserved.
OriginalFilename: generateConfig.exe
ProductName: XlsxMerger
